### ISSUE TITLE
Template should have nested lists

### ISSUE THREAD

**Issue by fulldecent** [dohliam/dropin-minimal-css#32]
Please included nested lists in the template.

```html
  <li>Top level
    <ul>
      <li>Inside</li>
    </ul>
  </li>
```

Some frameworks are not handling that properly. So preview will help.

**Comment by dohliam** [comment]
@fulldecent Thanks for the suggestion! This is a good idea -- would you be interested in submitting a PR to add nested lists to the template?

**Comment by bryancasler** [comment]
Finally I can help contribute, PR created https://github.com/dohliam/dropin-minimal-css/pull/43
