### ISSUE TITLE
Add IVORY

### ISSUE THREAD

**Issue by kanthvallampati** [dohliam/dropin-minimal-css#37]
IVORY (https://github.com/IVORY-UI/ivory) also one of the good framework, and you can consider to add in the list.

**Comment by dohliam** [comment]
@kanthvallampati Thank you for this suggestion! I tested out the CSS on our example page, but most of the elements appear to be unstyled or only partially styled (see screenshot below):

![image](https://user-images.githubusercontent.com/9295750/88656097-a1fa0900-d084-11ea-8427-a37a1e8b475d.png)

This was using the [CDN link](https://unpkg.com/ivoryui-ivory/ivory.min.css), but I also tried the minified version in the `dist` folder with the same result.

Is there a version of Ivory that can be used as a classless / minimal stylesheet (in other words, without needing to add classes to the HTML elements)?

**Comment by dohliam** [comment]
Closing as this does not appear to be classless CSS.
