### ISSUE TITLE
Add simple.css

### ISSUE THREAD

**Issue by fpsvogel** [dohliam/dropin-minimal-css#46]
I propose adding https://github.com/kevquirk/simple.css. It is similar to a lot of others on this list. (I'm not the author.)

**Comment by dohliam** [comment]
@fpsvogel Thanks for this suggestion! You're right that this is a perfect fit for this list. Although we already have a different [Simple CSS](https://github.com/tukangslicing/simplecss) listed, it seems to no longer be actively maintained, so I've replaced it with this one instead.
