### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by ghost** [dohliam/dropin-minimal-css#47]
I don't know if this is the right place to ask, sorry if not.

Most frameworks present horizontal scroll on mobile, which is annoying from a responsiveness perspective, including some that claim to be responsive. Is it because of this particular demo implementation or they aren't really as responsive as they claim to be?

**Comment by ghost** [comment]
Close.

**Comment by dohliam** [comment]
It looks like the horizontal scroll in most cases is the result of the large images and/or video in the [embedded content section](https://dohliam.github.io/dropin-minimal-css/#embedded) not being resized automatically by the CSS.

The frameworks that don't have horizontal scroll (like Bamboo) resize these images to fit the screen size, while others leave them at their original size. So, either using smaller images or setting a max-width for image elements would probably be enough to avoid this issue if you are planning to use one of the frameworks somewhere else.

Another thing I noticed is that the large table element in the in the [tabular data section](https://dohliam.github.io/dropin-minimal-css/#text__tables) sometimes causes horizontal scrolling if the CSS does not handle it properly. Of the frameworks without the scrolling issue, some of them have restricted the width of the table to the size of the window, and others have added an internal scroll to the table by setting `overflow: auto`.
