### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jcbhmr** [dohliam/dropin-minimal-css#54]
![image](https://user-images.githubusercontent.com/61068799/216208909-eb217017-13ba-46a4-9d13-5ba1d1428ae4.png)

![image](https://user-images.githubusercontent.com/61068799/216209358-706aa9ef-3fec-4136-8562-596631e4507a.png)

**Comment by dohliam** [comment]
@jcbhmr Are there any features or functionality you are missing? Feel free to submit a PR if there is anything you would like to add.
